version: '3'
services:
  jupyter-notebook:
    image: achalim/heart_disease_predictor_py:e5a77f6
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
