name: heart_disease_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - ipykernel
  - matplotlib
  - pandas
  - ipython
  - scikit-learn>=1.5.1
  - notebook=6.5.4
  - jupyterlab
  - altair-all
  - jupyter_contrib_nbextensions=0.7.0