name: heart_disease_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - ipykernel=6.26.0
  - matplotlib=3.9.2
  - pandas=2.1.2
  - ipython=8.21.0
  - scikit-learn=1.3.2
  - notebook=6.5.4
  - jupyterlab=4.3.1
  - jupyter_contrib_nbextensions=0.7.0
  - pandera=0.21.0
  - pip
  - pip:
    - deepchecks==0.18.1
